<?php
/**
 * GenerateBarcodeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * barcodeapi
 *
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * GenerateBarcodeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GenerateBarcodeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for generateBarcodeEAN13
     *
     * Generate a EAN-13 code barcode as PNG file.
     *
     */
    public function testGenerateBarcodeEAN13()
    {
    }

    /**
     * Test case for generateBarcodeEAN8
     *
     * Generate a EAN-8 code barcode as PNG file.
     *
     */
    public function testGenerateBarcodeEAN8()
    {
    }

    /**
     * Test case for generateBarcodeQRCode
     *
     * Generate a QR code barcode as PNG file.
     *
     */
    public function testGenerateBarcodeQRCode()
    {
    }

    /**
     * Test case for generateBarcodeUPCA
     *
     * Generate a UPC-A code barcode as PNG file.
     *
     */
    public function testGenerateBarcodeUPCA()
    {
    }

    /**
     * Test case for generateBarcodeUPCE
     *
     * Generate a UPC-E code barcode as PNG file.
     *
     */
    public function testGenerateBarcodeUPCE()
    {
    }
}
